version: '3.8'
services:
  php: 
    build: './docker/php'
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - ${PHP_PORT:-8080}:80
    volumes:
      - ./:/var/www/html
    command: php -S 0.0.0.0:80 -t .
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - mysql